export default {
  API: {
    PURPOSES_GET_ERROR: 'PURPOSES_GET_ERROR',
    PURPOSES_GET_REQUEST: 'PURPOSES_GET_REQUEST',
    PURPOSES_GET_SUCCESS: 'PURPOSES_GET_SUCCESS',

    RESERVATION_DELETE_ERROR: 'RESERVATION_DELETE_ERROR',
    RESERVATION_DELETE_REQUEST: 'RESERVATION_DELETE_REQUEST',
    RESERVATION_DELETE_SUCCESS: 'RESERVATION_DELETE_SUCCESS',

    RESERVATIONS_GET_ERROR: 'RESERVATIONS_GET_ERROR',
    RESERVATIONS_GET_REQUEST: 'RESERVATIONS_GET_REQUEST',
    RESERVATIONS_GET_SUCCESS: 'RESERVATIONS_GET_SUCCESS',

    RESERVATION_POST_ERROR: 'RESERVATION_POST_ERROR',
    RESERVATION_POST_REQUEST: 'RESERVATION_POST_REQUEST',
    RESERVATION_POST_SUCCESS: 'RESERVATION_POST_SUCCESS',

    RESERVATION_PUT_ERROR: 'RESERVATION_PUT_ERROR',
    RESERVATION_PUT_REQUEST: 'RESERVATION_PUT_REQUEST',
    RESERVATION_PUT_SUCCESS: 'RESERVATION_PUT_SUCCESS',

    RESOURCE_FAVORITE_POST_ERROR: 'RESOURCE_FAVORITE_POST_ERROR',
    RESOURCE_FAVORITE_POST_REQUEST: 'RESOURCE_FAVORITE_POST_REQUEST',
    RESOURCE_FAVORITE_POST_SUCCESS: 'RESOURCE_FAVORITE_POST_SUCCESS',

    RESOURCE_UNFAVORITE_POST_ERROR: 'RESOURCE_UNFAVORITE_POST_ERROR',
    RESOURCE_UNFAVORITE_POST_REQUEST: 'RESOURCE_UNFAVORITE_POST_REQUEST',
    RESOURCE_UNFAVORITE_POST_SUCCESS: 'RESOURCE_UNFAVORITE_POST_SUCCESS',

    RESOURCE_GET_ERROR: 'RESOURCE_GET_ERROR',
    RESOURCE_GET_REQUEST: 'RESOURCE_GET_REQUEST',
    RESOURCE_GET_SUCCESS: 'RESOURCE_GET_SUCCESS',

    RESOURCES_GET_ERROR: 'RESOURCES_GET_ERROR',
    RESOURCES_GET_REQUEST: 'RESOURCES_GET_REQUEST',
    RESOURCES_GET_SUCCESS: 'RESOURCES_GET_SUCCESS',

    SEARCH_RESULTS_GET_ERROR: 'SEARCH_RESULTS_GET_ERROR',
    SEARCH_RESULTS_GET_REQUEST: 'SEARCH_RESULTS_GET_REQUEST',
    SEARCH_RESULTS_GET_SUCCESS: 'SEARCH_RESULTS_GET_SUCCESS',

    UNITS_GET_ERROR: 'UNITS_GET_ERROR',
    UNITS_GET_REQUEST: 'UNITS_GET_REQUEST',
    UNITS_GET_SUCCESS: 'UNITS_GET_SUCCESS',

    USER_GET_ERROR: 'USER_GET_ERROR',
    USER_GET_REQUEST: 'USER_GET_REQUEST',
    USER_GET_SUCCESS: 'USER_GET_SUCCESS',
  },
  UI: {
    ADD_NOTIFICATION: 'ADD_NOTIFICATION',
    CANCEL_RESERVATION_EDIT: 'CANCEL_RESERVATION_EDIT',
    CHANGE_ADMIN_RESERVATIONS_FILTERS: 'CHANGE_ADMIN_RESERVATIONS_FILTERS',
    CHANGE_SEARCH_FILTERS: 'CHANGE_SEARCH_FILTERS',
    CLEAR_RESERVATIONS: 'CLEAR_RESERVATIONS',
    CLEAR_SEARCH_RESULTS: 'CLEAR_SEARCH_RESULTS',
    CLOSE_MODAL: 'CLOSE_MODAL',
    HIDE_NOTIFICATION: 'HIDE_NOTIFICATION',
    OPEN_MODAL: 'OPEN_MODAL',
    SELECT_RESERVATION_TO_CANCEL: 'SELECT_RESERVATION_TO_CANCEL',
    SELECT_RESERVATION_TO_EDIT: 'SELECT_RESERVATION_TO_EDIT',
    SELECT_RESERVATION_TO_SHOW: 'SELECT_RESERVATION_TO_SHOW',
    TOGGLE_TIME_SLOT: 'TOGGLE_TIME_SLOT',
  },
};
