export default {
  FETCH_RESOURCE_START: 'FETCH_RESOURCE_START',
  FETCH_RESOURCE_SUCCESS: 'FETCH_RESOURCE_SUCCESS',
  FETCH_RESOURCE_ERROR: 'FETCH_RESOURCE_ERROR',
  FETCH_RESOURCES_START: 'FETCH_RESOURCES_START',
  FETCH_RESOURCES_SUCCESS: 'FETCH_RESOURCES_SUCCESS',
  FETCH_RESOURCES_ERROR: 'FETCH_RESOURCES_ERROR',
};
