export default {
  FETCH_PURPOSES_START: 'FETCH_PURPOSES_START',
  FETCH_PURPOSES_SUCCESS: 'FETCH_PURPOSES_SUCCESS',
  FETCH_PURPOSES_ERROR: 'FETCH_PURPOSES_ERROR',
  FETCH_RESOURCE_START: 'FETCH_RESOURCE_START',
  FETCH_RESOURCE_SUCCESS: 'FETCH_RESOURCE_SUCCESS',
  FETCH_RESOURCE_ERROR: 'FETCH_RESOURCE_ERROR',
  FETCH_RESOURCES_START: 'FETCH_RESOURCES_START',
  FETCH_RESOURCES_SUCCESS: 'FETCH_RESOURCES_SUCCESS',
  FETCH_RESOURCES_ERROR: 'FETCH_RESOURCES_ERROR',
  FETCH_UNITS_START: 'FETCH_UNITS_START',
  FETCH_UNITS_SUCCESS: 'FETCH_UNITS_SUCCESS',
  FETCH_UNITS_ERROR: 'FETCH_UNITS_ERROR',
};
