export default {
  RESERVATION_CANCEL: 'RESERVATION_CANCEL',
  RESERVATION_CONFIRM: 'RESERVATION_CONFIRM',
  RESERVATION_COMMENT: 'RESERVATION_COMMENT',
  RESERVATION_INFO: 'RESERVATION_INFO',
  RESERVATION_SUCCESS: 'RESERVATION_SUCCESS',
  RESOURCE_TERMS: 'RESOURCE_TERMS',
};
