export default {
  RESERVATION_CANCEL: 'RESERVATION_CANCEL',
  RESERVATION_CONFIRM: 'RESERVATION_CONFIRM',
  RESERVATION_DELETE: 'RESERVATION_DELETE',
  RESERVATION_INFO: 'RESERVATION_INFO',
  RESERVATION_SUCCESS: 'RESERVATION_SUCCESS',
};
