name: varaamo-pr

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js lts/fermium (14)
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: Run CI checks
        run: |
          yarn install --frozen-lockfile
          yarn lint
          yarn test:ci
          docker build  -t varaamo .
          yarn build
        env:
          TZ: Europe/Helsinki
